# Generated by Django 6.0.2 on 2026-03-07 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('categoria', models.CharField(max_length=100)),
                ('articulacion_nacional', models.TextField(blank=True)),
                ('articulacion_regional', models.TextField(blank=True)),
                ('articulacion_municipal', models.TextField(blank=True)),
                ('articulacion_institucional', models.TextField(blank=True)),
                ('descripcion_detallada', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='soportes_estrategicos/')),
                ('tipo_documento', models.CharField(choices=[('PLAN', 'Plan de desarrollo'), ('LINEAMIENTO', 'Lineamiento'), ('POLITICA', 'Política'), ('OTRO', 'Otro documento')], max_length=20)),
                ('seccion', models.CharField(choices=[('INT', 'Internacional'), ('NAC', 'Nacional'), ('REG', 'Regional'), ('MUN', 'Municipal'), ('INS', 'Institucional')], max_length=5)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios.proyecto')),
            ],
        ),
    ]
