# Generated by Django 6.0.2 on 2026-08-07 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_proyecto_documentosoporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='leyes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='objetivos_desarrollo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='pais',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='riesgos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL),
        ),
    ]
