# Generated by Django 6.0.2 on 2026-08-26 18:57

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_proyecto_fecha_creacion_proyecto_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='diagnostico_antecedentes',
            field=models.TextField(blank=True, verbose_name='Antecedentes (últimos 5 años)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='diagnostico_cifras',
            field=models.TextField(blank=True, verbose_name='Cifras y datos estadísticos'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='diagnostico_fuentes',
            field=models.TextField(blank=True, help_text='URLs de las fuentes oficiales usadas para generar el diagnóstico.', verbose_name='Fuentes consultadas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='diagnostico_necesidades',
            field=models.TextField(blank=True, verbose_name='Necesidades y desafíos'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(validators=[usuarios.models.validar_descripcion_minima]),
        ),
    ]
